name: lab7_seq
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - pip
  - pip:
      - tensorflow-macos==2.13.0
      - tensorflow-metal==1.1.0
      - datasets==2.14.5
      - regex==2023.6.3
      - tqdm==4.66.1
